tas:
  - name: Shai Szulanski 
    email: sszulanski@college.harvard.edu
  - name: Jeffrey Ling
    email: jling@college.harvard.edu
  - name: Samuel Cheng
    email: samuelcheng@college.harvard.edu
  - name: Ankit Gupta
    email: ankitgupta@college.harvard.edu
  - name: Aidi Zhang
    email: aidizhang@college.harvard.edu
  - name: Lily Zhang
    email: lilyhongzhang@college.harvard.edu
  - name: Frances Ding
    email: francesding@college.harvard.edu
  - name: Mark Goldstein
    email: goldstein.mark@gmail.com
  - name: Charles Liu
    email: charlesliu@college.harvard.edu
  - name: Jeffrey Chang
    email: jeffreychang@college.harvard.edu
  - name: Fanney Zhu
    email: fanneyzhu@college.harvard.edu
  - name: Carl Denton        
    email: carldenton@college.harvard.edu


dates: ["", "Jan. 24", "Jan. 26", "Jan. 31", "Feb. 2", "Feb. 7", "Feb. 9",  "Feb. 14", "Feb. 16",
        "Feb. 21", "Feb. 23", "Feb. 28", "Mar. 2", "Mar. 7", "Mar. 9", "Mar. 21", 
        "Mar. 23", "Mar. 28", "Mar. 30", "Apr. 4", "Apr. 6", "Apr. 11", "Apr. 13", "Apr. 18", "Apr. 20", "Apr. 25"]


ohs:
  - time: Mon 6-8pm
    location: MD 119
  - time: Tue 8-10pm
    location: Eliot DH
  - time: Wed 9-11pm
    location: Quincy DH
  - time: Thu 8-10pm
    location: Currier DH
  - time: Sun 8-10pm
    location: Piazza
           
lectures:
  - topic: <a href="https://CS287.github.io/Lectures/slides/lecture1.pdf" >Machine Learning</a>
    subtopic: Supervised Learning
    hw: 
    papers:
  - topic: Regression
    subtopic: Linear Regression 1
    hw: 
    papers:
  - topic: 
    subtopic: Linear Regression 2
    hw: 
    papers:
  - topic: Model Selection
    subtopic: Model Selection
    hw: T1 <a href="https://canvas.harvard.edu/courses/21992/assignments/117075">Regression</a>
    papers:
  - topic: 
    subtopic: Bayesian Linear Regression
    hw: 
    papers:
  - topic: 
    subtopic: Model Regularization
    hw: P1 <a href="https://canvas.harvard.edu/courses/21992/assignments/117077">Regression</a> (<a href="https://inclass.kaggle.com/c/cs181-regression-practical">Kaggle</a>) 
    papers:
  - topic: Classification
    subtopic: Linear Classification
    hw: 
    papers:
  - topic: 
    subtopic: Probabilistic Classification
    hw: 
    papers:
  - topic: Neural Networks
    subtopic: Neural Networks 1
    hw: 
    papers:
  - topic: 
    subtopic: Neural Networks 2
    hw: T2 <a href="https://canvas.harvard.edu/courses/21992/assignments/117078">Classification</a> due
    papers:
  - topic: Margin-Based Models
    subtopic: Max-Margin Classification
    hw: 
    papers:
  - topic: 
    subtopic: Support Vector Machines
    hw: P2 <a href="https://canvas.harvard.edu/courses/21992/assignments/117079">Classification</a> (<a href="https://inclass.kaggle.com/c/cs-181-classification-practical">Kaggle</a>)
    papers:
  - topic: 
    subtopic: Midterm 1
    hw: 
    papers:
  - topic: Clustering
    subtopic: K-Means
    hw: 
    papers:
  - topic: 
    subtopic: Hierarchical Clustering
    hw: 
    papers:
  - topic: Unsupervised Learning
    subtopic: PCA
    hw: T3 <a href="https://canvas.harvard.edu/courses/21992/assignments/117080">SVMs</a> due
    papers:
  - topic: 
    subtopic: Mixture Models, EM
    hw: 
    papers:
  - topic: 
    subtopic: Topic Models
    hw: T4 <a href="https://canvas.harvard.edu/courses/21992/assignments/117081">Clustering</a> due
    papers:
  - topic: Graphical Models
    subtopic: HMMs
    hw: 
    papers:
  - topic: 
    subtopic: Bayesian Networks
    hw: P3 <a href="https://canvas.harvard.edu/courses/21992/assignments/117083">Unsupervised</a> (<a href="https://inclass.kaggle.com/c/cs-181-unsupervised-practical">Kaggle</a>) 
    papers:
  - topic: Reinforcement Learning
    subtopic: MDP / Value and Policy Iteration
    hw: 
    papers:
  - topic: 
    subtopic: Reinforcement Learning
    hw: T5 <a href="https://canvas.harvard.edu/courses/21992/assignments/117082">Probabilistic Models</a> Due
    papers:
  - topic: 
    subtopic: POMDPs 
    hw: 
    papers:
  - topic: 
    subtopic: Wrap-Up
    hw: 
    papers:
  - topic: 
    subtopic: Midterm 2
    hw: P4 <a href="https://canvas.harvard.edu/courses/21992/assignments/117084">RL</a> (<a href="https://inclass.kaggle.com/c/cs-181-rl-practical">Kaggle</a>)
    papers:

