tas:
  - name: Shai Szulanski 
    email: sszulanski@college.harvard.edu


dates: ["", "Jan. 24", "Jan. 26", "Jan. 31", "Feb. 2", "Feb. 7", "Feb. 9", "Feb. 11", "Feb. 14", "Feb. 16",
        "Feb. 24", "Feb. 28", "Mar. 2", "Mar. 7", "Mar. 9", "Mar. 21", 
        "Mar. 23", "Mar. 28", "Mar. 30", "Apr. 4", "Apr. 6", "Apr. 11", "Apr. 13", "Apr. 18", "Apr. 20", "Apr. 25"]


ohs:
  - time: Mon 6-8pm
    location: MD 119
  - time: Tue 8-10pm
    location: Eliot DH
  - time: Wed 9-11pm
    location: Quincy DH
  - time: Thu 8-10pm
    location: Currier DH
  - time: Sun 8-10pm
    location: Piazza
           
lectures:
  - topic: <a href="https://CS287.github.io/Lectures/slides/lecture1.pdf" >Machine Learning</a>
    subtopic: Supervised Learning
    hw: 
    papers:
  - topic: Regression
    subtopic: Linear Regression 1
    hw: 
    papers:
  - topic: 
    subtopic: Linear Regression 2
    hw: 
    papers:
  - topic: Model Selection
    subtopic: Model Selection
    hw: 
    papers:
  - topic: 
    subtopic: Bayesian Linear Regression
    hw: 
    papers:
  - topic: 
    subtopic: Model Regularization
    hw: 
    papers:
  - topic: Classification
    subtopic: Linear Classification
    hw: 
    papers:
  - topic: 
    subtopic: Probabilistic Classification
    hw: 
    papers:
  - topic: Neural Networks
    subtopic: Neural Networks 1
    hw: 
    papers:
  - topic: 
    subtopic: Neural Networks 2
    hw: 
    papers:
  - topic: Margin-Based Models
    subtopic: Max-Margin Classification
    hw: 
    papers:
  - topic: 
    subtopic: Support Vector Machines
    hw: 
    papers:
  - topic: 
    subtopic: Midterm 1
    hw: 
    papers:
  - topic: Clustering
    subtopic: K-Means
    hw: 
    papers:
  - topic: 
    subtopic: Hierarchical Clustering
    hw: 
    papers:
  - topic: Unsupervised Learning
    subtopic: PCA
    hw: 
    papers:
  - topic: 
    subtopic: Mixture Models, EM
    hw: 
    papers:
  - topic: 
    subtopic: Topic Models
    hw: 
    papers:
  - topic: Graphical Models
    subtopic: HMMs
    hw: 
    papers:
  - topic: 
    subtopic: Bayesian Networks
    hw: 
    papers:
  - topic: RL
    subtopic: MDP / Value and Policy Iteration
    hw: 
    papers:
  - topic: 
    subtopic: Reinforcement Learning
    hw: 
    papers:
  - topic: 
    subtopic: POMDPs 
    hw: 
    papers:
  - topic: 
    subtopic: Wrap-Up
    hw: 
    papers:
  - topic: 
    subtopic: Midterm 2
    hw: 
    papers:

