tas:
  - name: Shai Szulanski 
    email: 
  - name: Jeffrey Ling
    email: 
  - name: Samuel Cheng
    email: 
  - name: Ankit Gupta
    email: 
  - name: Aidi Zhang
    email: 
  - name: Lily Zhang
    email: 
  - name: Frances Ding
    email: 
  - name: Mark Goldstein
    email: 
  - name: Charles Liu
    email: 
  - name: Jeffrey Chang
    email: 
  - name: Fanney Zhu
    email: 
  - name: Christine Hwang
    email: 


dates: ["", "Jan. 24", "Jan. 26", "Jan. 31", "Feb. 2", "Feb. 7", "Feb. 9",  "Feb. 14", "Feb. 16",
        "Feb. 21", "Feb. 23", "Feb. 28", "Mar. 2", "Mar. 7", "Mar. 9", "Mar. 21", 
        "Mar. 23", "Mar. 28", "Mar. 30", "Apr. 4", "Apr. 6", "Apr. 11", "Apr. 13", "Apr. 18", "Apr. 20", "Apr. 25"]


ohs:
  - time: Tue 7-9pm
    location: Quincy DH
  - time: Wed 5-7pm
    location: MD 119
  - time: Thu 7-9pm
    location: Currier DH
  - time: Thu 7-9pm
    location: Eliot DH
  - time: Fri 10-Noon
    location: MD Lounge
           
lectures:
  - topic: Machine Learning
    subtopic: 
    hw: 
    papers:
  - topic: Regression
    subtopic: <a href="lectures/02-lectures-lr.pdf">Linear Regression 1</a>
    hw: 
    papers: Bishop &sect; 3.1, Sklearn &sect; 3.1, 18.10
  - topic: 
    subtopic: <a href="lectures/03-lectures-lr.pdf">Linear Regression 2</a>
    hw: 
    papers: Bishop &sect; 2.3, 3.1
  - topic: Model Regularization
    subtopic: <a href="lectures/04-lectures-model.pdf">Model Selection</a>
    hw: T1 <a href="hw/homework1-regression.pdf">Regression</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117075">submit</a>)
    papers:
  - topic: 
    subtopic: <a href="lectures/05-lectures-blr.pdf">Bayesian Linear Regression</a>
    hw: 
    papers: Bishop &sect; 3.3
  - topic: Classification
    subtopic: <a href="lectures/06-lectures-class.pdf">Linear Classification</a>
    hw: P1 <a href="hw/practical1-regression.pdf">Regression</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117077">submit</a> | <a href="https://inclass.kaggle.com/c/cs181-regression-practical">kaggle</a>) 
    papers: Bishop &sect; 4.1, Sklearn &sect;  15.9
  - topic: 
    subtopic: <a href="lectures/07-lectures-class.pdf">Probabilistic Classification</a>
    hw: 
    papers: Bishop &sect; 4.2, 4.3, Sklearn &sect;  18.1, 29.24
  - topic: Neural Networks
    subtopic: <a href="lectures/08-lectures-nn1.pdf">Neural Networks 1</a>
    hw: 
    papers: Bishop &sect; 5.1-5.2
  - topic: 
    subtopic: <a href="lectures/09-lectures-nn2.pdf">Neural Networks 2</a>
    hw: 
    papers: Bishop &sect; 5.3
  - topic: Margin-Based Models
    subtopic: <a href="lectures/10-lectures-margin.pdf">Margin-Based Classification</a>
    hw: T2 <a href="hw/homework2-classification.pdf">Classification</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117078">submit</a>)
    papers:
  - topic: 
    subtopic: <a href="lectures/11-lectures-svm.pdf">Support Vector Machines</a>
    hw: 
    papers:
  - topic: 
    subtopic: <a href="lectures/12-lectures-deeplearning.pdf">Deep Learning</a>
    hw: P2 <a href="hw/practical2-classification">Classification</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117079">submit</a> | <a href="https://inclass.kaggle.com/c/cs-181-classification-practical">kaggle</a>)
    papers: 
  - topic: 
    subtopic: Midterm 1
    hw: 
    papers:
  - topic: Clustering
    subtopic: K-Means
    hw: 
    papers:
  - topic: 
    subtopic: Mixture Models, EM
    hw: 
    papers:
  - topic: 
    subtopic: Topic Models
    hw: T3 <a href="hw/homework3-svm.pdf">SVMs</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117080">submit</a>)
    papers:
  - topic: 
    subtopic: PCA
    hw: 
    papers:
  - topic: 
    subtopic: Hierarchical Clustering
    hw: T4 <a href="">Clustering</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117081">submit</a>)
    papers:
  - topic: Graphical Models
    subtopic: HMMs
    hw: 
    papers:
  - topic: 
    subtopic: Bayesian Networks
    hw: P3 <a href="">Unsupervised</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117083">submit</a> | <a href="https://inclass.kaggle.com/c/cs-181-unsupervised-practical">kaggle</a>) 
    papers:
  - topic: Reinforcement Learning
    subtopic: MDP / Value and Policy Iteration
    hw: 
    papers:
  - topic: 
    subtopic: Reinforcement Learning
    hw: T5 <a href="">EM</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117082">submit</a>)
    papers:
  - topic: 
    subtopic: Deep RL 
    hw: 
    papers:
  - topic: 
    subtopic: Wrap-Up
    hw: 
    papers:
  - topic: 
    subtopic: Midterm 2
    hw: P4 <a href="">RL</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117084">submit</a> | <a href="https://inclass.kaggle.com/c/cs-181-rl-practical">kaggle</a>)
    papers:

